[package]
name = "hello_world"
description = "A minimal example of application development with Hearth GPUI."
version = "0.5.1"
publish = false
edition.workspace = true

[dependencies]
anyhow.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
hearth-gpui = { workspace = true }

[lints]
workspace = true
