[package]
name = "hearth-gpui-webview"
description = "WebView support for GPUI, based on Wry."
keywords = ["webview", "gpui","wry"]
license = "Apache-2.0"
documentation = "https://docs.rs/hearth-gpui-webview"
homepage = "https://jonzhang3.github.io/hearth-gpui"
repository = "https://github.com/JonZhang3/hearth-gpui/tree/main/crates/webview"
readme = "README.md"
edition.workspace = true
publish = true
version = "0.5.0"

[features]
inspector = ["wry/devtools"]

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
gpui.workspace = true
wry = { version = "0.53.3", package = "lb-wry" }
